# 📚 Librería `numpy` (Numerical Python)
- **Crear y manejar `ndarray`:** arrays multidimensionales eficientes (arrays -1 dimensión-, matrices -2 dimensiones-, tensores -3 dimensiones o más-).
  - <u>Ventajas:</u>
    - Rapidez: Las operaciones son mucho más rápidas
    - Memoria: Ocupan menos memoria
  - <u>Desventajas:</u>
    - Todos los elementos deben ser del mismo tipo de dato (y si no lo son, se toman como string)
- **Operaciones vectoriales:** Funciones matemáticas para operar sobre arrays sin necesidad de bucles.
  - Ejemplo: *Multiplicar un valor escalar (p.ej. 2) por una matriz (-2 dimensiones-)*
- **Operaciones matemáticas:**
  - Álgebra lineal: `dot`, `T`, `@`
  - Estadística: `mean`, `sum`, `std`, `min`, `max`
  - Generación de números aleatorios
  - Manipulación de arrays: `reshape`, `astype`, `copy`
  - Indexación y filtrado: Potente para seleccionar datos.
  - Funciones matemáticas: `np.sqrt`, `np.sin`, `np.exp`
  - Broadcasting: Operar entre arrays de diferentes tamaños sin copiar datos.
  - Creación rápida de arrays: `arange`, `zeros`, `ones`, `full`, `eye`, `linspace`
  - Manejo de missings e infinitos: `np.nan`, `np.inf`, `np.isnan`, `np.isfinite`

## <span style="color:#4A90E2;"><b>📦 Librerías</b></span>

In [1]:
# Librerías
import numpy as np

## <span style="color:#4A90E2;"><b>⚙️ Configuración inicial</b></span>

In [ ]:
# Configuración inicial
np.random.seed(12345) # Semilla para la generación de números aleatorios (para reproducibilidad)
np.set_printoptions(precision=4, suppress=True) # Precision de 4 decimales y sin notación científica

## <span style="color:#4A90E2;"><b>💻 Código</b></span>

### 🧱 Creación de estructuras

#### a. Arrays

In [23]:
# Array (unidimensional)
arr = np.arange(10)
print("Array:", arr)
print("Dimensiones:", arr.ndim)
print("Forma:", arr.shape)
print("Tipo:", arr.dtype)

# Multiplicar un array por un escalar
print("Operación con escalar - Array * 2:", arr * 2)

Array: [0 1 2 3 4 5 6 7 8 9]
Dimensiones: 1
Forma: (10,)
Tipo: int64
Operación con escalar - Array * 2: [ 0  2  4  6  8 10 12 14 16 18]


#### b. Matrices

In [25]:
# Matriz (vector bidimensional)
mat = np.array([[1.5, -0.1, 3.],
                [0., -3., 6.5]])
print("Matriz:", mat)
print("Dimensiones:", mat.ndim)
print("Forma:", mat.shape)
print("Tipo:", mat.dtype)

# Multiplicar la matriz por un escalar
print("Operación con escalar - Matriz * 2: ", mat * 2)

Matriz: [[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]
Dimensiones: 2
Forma: (2, 3)
Tipo: float64
Operación con escalar - Matriz * 2:  [[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


#### c. Tensores (permiten trabajar con las dimensiones que se quieran)
P.e: 100 Fotografías x Ancho(pix) x Alto(pix), x Nº colores/canales

In [ ]:
# Tensores (3 dimensiones o más)
tensor = np.arange(24).reshape((2, 3, 4)) # 2 bloques, 3 filas y 4 columnas. Puede seguir creciendo. (añadiendo por la izquierda, 4-> grupos, etc...)
print("Tensor 3D: ", tensor)
print("Dimensiones del tensor:", tensor.ndim)
print("Forma del tensor:", tensor.shape)
print("Tipo:", tensor.dtype)


Tensor 3D:  [[[[[ 0  1  2  3]
    [ 4  5  6  7]
    [ 8  9 10 11]]

   [[12 13 14 15]
    [16 17 18 19]
    [20 21 22 23]]]]]
Dimensiones del tensor: 5
Forma del tensor: (1, 1, 2, 3, 4)
Tipo: int64


### ⚡ Creación rápida de arrays

In [44]:
print("\nArray de 0s - np.zeros((2,3)): ", np.zeros((2,3))) # Crea un array de 2 filas y 3 columnas lleno de 0s
print("\nArray de 1s - np.ones((2,3)): ", np.ones((2,3))) # Crea un array de 2 filas y 3 columnas lleno de 1s
print("\nArray de 7s - np.full((2,3), 7)): ", np.full((2,3), 7)) # Crea un array de 2 filas y 3 columnas lleno de 7s
print("\nMatriz identidad - np.eye(3)): ", np.eye(3)) # Crea una matriz identidad de 3x3
print("\nArray con valores espaciados - np.linspace(0, 1, 5): ", np.linspace(0, 1, 5)) # Crea un array de 5 elementos igualmente espaciados entre 0 y 1 (inclusive)


Array de 0s - np.zeros((2,3)):  [[0. 0. 0.]
 [0. 0. 0.]]

Array de 1s - np.ones((2,3)):  [[1. 1. 1.]
 [1. 1. 1.]]

Array de 7s - np.full((2,3), 7)):  [[7 7 7]
 [7 7 7]]

Matriz identidad - np.eye(3)):  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array con valores espaciados - np.linspace(0, 1, 5):  [0.   0.25 0.5  0.75 1.  ]


### 🚀 Comparación de rendimiento

In [7]:
# Comparación de rendimiento entre un array de NumPy y una lista de Python
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%timeit my_arr * 2
%timeit [x * 2 for x in my_list]

3.54 ms ± 118 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
60.7 ms ± 6.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 🔤 Tipos de dato y conversión

In [35]:
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = arr_int.astype(np.float64)
print("Tipo nativo - arr_int dtype:", arr_int.dtype)
print("Conversión - arr_float:", arr_float, "dtype:", arr_float.dtype)

numeric_strings = np.array(["1.25", "-9.6", "42", "1e3"])
print("Tipo nativo - numeric_strings dtype:", numeric_strings.dtype)
print("Conversión - numeric_strings -> float: ", numeric_strings.astype(float))

Tipo nativo - arr_int dtype: int32
Conversión - arr_float: [1. 2. 3.] dtype: float64
Tipo nativo - numeric_strings dtype: <U4
Conversión - numeric_strings -> float:  [   1.25   -9.6    42.   1000.  ]


### ➕ Operaciones vectoriales y matemáticas

#### a. Operaciones con Arrays

In [9]:
arr = np.arange(1, 5)
print("Array generado - arr:", arr)
print("Suma con escalar - arr + 10:", arr + 10)
print("Producto de arrays - arr * arr:", arr * arr)
print("División por escalar - arr / 2:", arr / 2)
print("Potencia - arr ** 2:", arr ** 2)
print("Raíz cuadrada - np.sqrt(arr):", np.sqrt(arr))
print("Exponencial - np.exp(arr):", np.exp(arr))
print("Seno - np.sin(arr):", np.sin(arr))

Array generado - arr: [1 2 3 4]
Suma con escalar - arr + 10: [11 12 13 14]
Producto de arrays - arr * arr: [ 1  4  9 16]
División por escalar - arr / 2: [0.5 1.  1.5 2. ]
Potencia - arr ** 2: [ 1  4  9 16]
Raíz cuadrada - np.sqrt(arr): [1.     1.4142 1.7321 2.    ]
Exponencial - np.exp(arr): [ 2.7183  7.3891 20.0855 54.5982]
Seno - np.sin(arr): [ 0.8415  0.9093  0.1411 -0.7568]


#### b. Operaciones con Matrices

In [20]:
# Operaciones con matrices
matriz_a = np.array([[1, 2], [3, 4]])
matriz_b = np.array([[5, 6], [7, 8]])

print("Matriz A:")
print(matriz_a)
print("\nMatriz B:")
print(matriz_b)
print("\nSuma de matrices:")
print(matriz_a + matriz_b)
print("\nResta de matrices:")
print(matriz_a - matriz_b)
print("\nProducto elemento a elemento:")
print(matriz_a * matriz_b)
print("\nProducto matricial:")
print(matriz_a @ matriz_b)
print("\nTranspuesta de A:")
print(matriz_a.T)

Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[5 6]
 [7 8]]

Suma de matrices:
[[ 6  8]
 [10 12]]

Resta de matrices:
[[-4 -4]
 [-4 -4]]

Producto elemento a elemento:
[[ 5 12]
 [21 32]]

Producto matricial:
[[19 22]
 [43 50]]

Transpuesta de A:
[[1 3]
 [2 4]]


#### c. Operaciones con Tensores

In [21]:
# Operaciones con tensores
# Tensor de forma (2, 2, 3)
tensor_a = np.arange(12).reshape((2, 2, 3))
tensor_b = np.arange(12, 24).reshape((2, 2, 3))

print("Tensor A:")
print(tensor_a)
print("\nTensor B:")
print(tensor_b)
print("\nSuma de tensores:")
print(tensor_a + tensor_b)
print("\nProducto elemento a elemento:")
print(tensor_a * tensor_b)
print("\nEscalado del tensor A por 2:")
print(tensor_a * 2)

Tensor A:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Tensor B:
[[[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]

Suma de tensores:
[[[12 14 16]
  [18 20 22]]

 [[24 26 28]
  [30 32 34]]]

Producto elemento a elemento:
[[[  0  13  28]
  [ 45  64  85]]

 [[108 133 160]
  [189 220 253]]]

Escalado del tensor A por 2:
[[[ 0  2  4]
  [ 6  8 10]]

 [[12 14 16]
  [18 20 22]]]


#### Broadcasting (entre dimensiones diferentes)

In [41]:
mat = np.arange(6).reshape((2, 3))
print("Matriz:", mat)
print("\nSumar un vector fila a cada fila de la matriz: ", mat + np.array([10, 20, 30]))
print("\nMultiplicar una columna: ", mat * np.array([[2], [3]]))

Matriz: [[0 1 2]
 [3 4 5]]

Sumar un vector fila a cada fila de la matriz:  [[10 21 32]
 [13 24 35]]

Multiplicar una columna:  [[ 0  2  4]
 [ 9 12 15]]


### 🧮 Álgebra lineal

In [39]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
b = np.arange(6).reshape((3, 2))
print("\nMatriz a:", a)
print("\nMatriz b:", b)
print("\nTraspuesta - a.T:", a.T)
print("\nTraspuesta - b.T:", b.T)
print("\nProducto matricial - a @ b:", a @ b)
print("\nProducto - np.dot(a, b):", np.dot(a, b))


Matriz a: [[1. 2. 3.]
 [4. 5. 6.]]

Matriz b: [[0 1]
 [2 3]
 [4 5]]

Traspuesta - a.T: [[1. 4.]
 [2. 5.]
 [3. 6.]]

Traspuesta - b.T: [[0 2 4]
 [1 3 5]]

Producto matricial - a @ b: [[16. 22.]
 [34. 49.]]

Producto - np.dot(a, b): [[16. 22.]
 [34. 49.]]


### 📊 Funciones estadísticas

In [46]:
stats = np.array([[1., 2., 3.], [4., 5., 6.]])
print("\nSumatorio - np.sum(stats):", np.sum(stats))
print("\nMedia - np.mean(stats):", np.mean(stats))
print("\nDesviación estándar - np.std(stats):", np.std(stats))
print("\nMínimo - np.min(stats):", np.min(stats))
print("\nMáximo - np.max(stats):", np.max(stats))
print("\nSuma acumulativa - np.cumsum(stats):", np.cumsum(stats))
print("\nMedia por columna - np.mean(stats, axis=0):", np.mean(stats, axis=0))


Sumatorio - np.sum(stats): 21.0

Media - np.mean(stats): 3.5

Desviación estándar - np.std(stats): 1.707825127659933

Mínimo - np.min(stats): 1.0

Máximo - np.max(stats): 6.0

Suma acumulativa - np.cumsum(stats): [ 1.  3.  6. 10. 15. 21.]

Media por columna - np.mean(stats, axis=0): [2.5 3.5 4.5]


### 🎯 Indexación y filtrado (slicing)

#### a. Indexación y filtrado con arrays

In [50]:
arr = np.arange(10)
print("Array original:", arr)
print("Indexado simple - arr[4]:", arr[4])
print("Indexado porción - arr[5:8]:", arr[5:8])
arr[5:8] = 12
print("Array tras modificar una porción [5:8]:", arr)
arr_slice = arr[5:8]
arr_slice[:] = 0
print("Array tras modificar el slice (copia de tipo índice de memoria):", arr)
arr_copy = arr[5:8].copy() # Así se crea una copia real e independiente
arr_copy[:] = 99
print("Array copia (copia de contenido):", arr_copy)
print("Array original no se modifica:", arr)

Array original: [0 1 2 3 4 5 6 7 8 9]
Indexado simple - arr[4]: 4
Indexado porción - arr[5:8]: [5 6 7]
Array tras modificar una porción [5:8]: [ 0  1  2  3  4 12 12 12  8  9]
Array tras modificar el slice (copia de tipo índice de memoria): [0 1 2 3 4 0 0 0 8 9]
Array copia (copia de contenido): [99 99 99]
Array original no se modifica: [0 1 2 3 4 0 0 0 8 9]


#### b. Indexación y filtrado con matrices

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz original:", arr2d)
print("Indexado simple - arr2d[2]:", arr2d[2])
print("Indexado doble - arr2d[2][2]:", arr2d[2][2])
print("Indexado porción - arr2d[:2, 1:]:", arr2d[:2, 1:])

arr2d[2]: [7 8 9]
arr2d[2][2]: 9
arr2d[:2, 1:]: [[2 3]
 [5 6]]


#### c. Indexación y filtrado con tensores

In [59]:
# Indexación y filtrado con tensores
# Crear un tensor 3D de forma (2, 3, 4)
tensor = np.arange(24).reshape((2, 3, 4))

print("Tensor original:")
print(tensor)
print("\nAcceso a un elemento concreto - tensor[0, 1, 2]:", tensor[0, 1, 2])
print("\nSeleccionar una capa completa - tensor[1, :, :]:")
print(tensor[1, :, :])
print("\nSeleccionar una sección de todas las capas - tensor[:, 1, :]:")
print(tensor[:, 1, :])
print("\nPorción en 3D - tensor[0, 1:, 1:3]:")
print(tensor[0, 1:, 1:3])

# Filtrado booleano sobre el tensor
mask = tensor > 10
print("\nMáscara booleana (tensor > 10):")
print(mask)
print("\nValores que cumplen la condición - tensor[mask]:")
print(tensor[mask])

Tensor original:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Acceso a un elemento concreto - tensor[0, 1, 2]: 6

Seleccionar una capa completa - tensor[1, :, :]:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Seleccionar una sección de todas las capas - tensor[:, 1, :]:
[[ 4  5  6  7]
 [16 17 18 19]]

Porción en 3D - tensor[0, 1:, 1:3]:
[[ 5  6]
 [ 9 10]]

Máscara booleana (tensor > 10):
[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]

Valores que cumplen la condición - tensor[mask]:
[11 12 13 14 15 16 17 18 19 20 21 22 23]


#### d. Filtrado booleano (por condición)

In [60]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
print("\nArray de nombres:", names)
print("\nMatriz de datos (tiene 7 filas, que coinciden con los nombres):", data)
print("\nFiltrado por condición en Arrays - names == 'Bob':", names == "Bob")
print("\nFiltrado en Matriz con array (máscara) booleano - data[names == 'Bob']:", data[names == "Bob"])
print("\nFiltrado por condición en Matriz - data[data < 0]:", data[data < 0])
data[data < 0] = 0
print("\nMatriz de datos tras eliminar negativos:", data)


Array de nombres: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Matriz de datos (tiene 7 filas, que coinciden con los nombres): [[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]

Filtrado por condición en Arrays - names == 'Bob': [ True False False  True False False False]

Filtrado en Matriz con array (máscara) booleano - data[names == 'Bob']: [[4 7]
 [0 0]]

Filtrado por condición en Matriz - data[data < 0]: [ -5 -12  -4]

Matriz de datos tras eliminar negativos: [[4 7]
 [0 2]
 [0 6]
 [0 0]
 [1 2]
 [0 0]
 [3 4]]


### ❓ Manejo de missings e infinitos

In [62]:
vals = np.array([1., 2., np.nan, np.inf, -np.inf, 5.])
print("Array con distintos valores especiales:", vals)
print("\nValores NaN - isnan:", np.isnan(vals))
print("\nValores finitos - isfinite:", np.isfinite(vals))
print("\nMedia ignorando NaN - nanmean:", np.nanmean(vals))
print("\nSuma ignorando NaN - nansum:", np.nansum(vals))
print("\nReemplazar NaN por 0 - nan_to_num:", np.nan_to_num(vals, nan=0.0))

Array con distintos valores especiales: [  1.   2.  nan  inf -inf   5.]

Valores NaN - isnan: [False False  True False False False]

Valores finitos - isfinite: [ True  True False False False  True]

Media ignorando NaN - nanmean: nan

Suma ignorando NaN - nansum: nan

Reemplazar NaN por 0 - nan_to_num: [ 1.0000e+000  2.0000e+000  0.0000e+000  1.7977e+308 -1.7977e+308
  5.0000e+000]


### 🎲 Generación de números aleatorios

In [64]:
# Distribución normal estándar
samples = np.random.standard_normal(size=(4,4))
print("\nDistribución normal estándar:", samples)

# Distribución uniforme
samples_uni = np.random.uniform(size=(4,4))
print("\nDistribución uniforme:", samples_uni)

# Distribución binomial
samples_bino = np.random.binomial(n=10, p=0.5, size=(4,4))
print("\nDistribución binomial:", samples_bino)

# Distribución gamma
samples_gamma = np.random.gamma(shape=10, scale=0.3, size=(4,4))
print("\nDistribución gamma:", samples_gamma)


Distribución normal estándar: [[ 0.508  -0.6534  0.187  -0.3917]
 [-0.2723 -0.0171  0.6803  0.6355]
 [-0.7572  0.7181 -0.3043 -1.6778]
 [ 0.427  -1.5637 -0.3675  1.0459]]

Distribución uniforme: [[0.4325 0.8326 0.3711 0.0406]
 [0.5547 0.4512 0.7253 0.3785]
 [0.8407 0.4693 0.5626 0.6612]
 [0.4622 0.6236 0.2219 0.7329]]

Distribución binomial: [[5 4 4 4]
 [3 6 4 3]
 [6 5 6 6]
 [4 4 4 3]]

Distribución gamma: [[2.2676 2.2722 3.626  3.8354]
 [4.2853 3.1417 3.1982 2.3941]
 [1.9408 2.1965 2.2537 2.7781]
 [2.4634 4.2171 2.1797 3.4999]]
